### ISSUE TITLE
undefined user object returned every time. This is allowing duplicate emails in the database. 

### ISSUE THREAD

**Issue by ruchit2801** [pranavpandey1998official/serverSEN#1]
In the `signup` route in `routs/user.js`, the user object in the `const signUp = async(req, res)` function is always undefined. 
Bug is present in the following part. 
```js
user = await User.findUser(email);
    console.log("user: "+user);
    if(user!=null && user[0].is_verified) {
      return res.status(402).json({
        error: true,
        message: "email already exists"
      })
```
Here by some reason, `user` object is always undefined. This results in never raising the `email already exists` error, and hence, allowing to create multiple users with the same email. 

**How to reproduce?**
To reproduce, you can send two post requests with same `req.body` as follows from postman. Do remember to change the userId while sending different requests.
```json
{
	"userData" : {
		"userId" : 2,
		"password" : "alice",
		"email" : "alice@example.com",
		"firstName" : "alice",
		"lastName" : "green", 
		"is_verified" : false,
		"created_at" : 1585926378
	}
}
```
Or, you can also see by doing `console.log(user)`, and make multiple requests in some file and then run it. You will see that duplicate entries in the database will be created and user object will always print out as undefined in the console. This behaviour never blocks the sign up requests for duplicate emails. 

Possible reason : 
One possible reason I think is :  In the functions written in the `user.model.js`, any function is not returning anything to its caller. For example, consider following function : 

```js
xports.findUser = async(email) => {
	const query = {
		sql: 'SELECT * FROM users WHERE email=?',
		values: [email],
	}
	connection.query(query, (err, result) => {
		console.log(result);
		if(err) throw err;
		else return result;
	})
}
```

It is not returning anything explicitly to its caller. I don't know if you return object in `connection.query`, it's also returned by the function `findUser`. This function should somehow create the user object fetched from the database and return it explicitly.

**Comment by pranavpandey1998official** [comment]
@kaushil return a promise just like we did with property model

**Comment by ruchit2801** [comment]
@pranavpandey1998official This problem seems to be solved in recent commit. So closing this. @kaushil next up is to add validators for emails. Tests are failing for invalid emails. I will soon make a PR with all the tests, so that you get more insights on where tests are failing.
